chore(setting-project): company 프로젝트 세팅
EntryDSM/Buldak pull request #15
Opened 2022-06-30 07:54 UTC by justinlee05

2022-07-01 02:38 UTC, kimulchan requested changes

2022-07-01 02:38 UTC, kimulchan commented on apps/company/styles/globalStyle.ts
> +`;
global styled 은 emotion style provider 를 이용해 주세요!

2022-07-01 02:38 UTC, kimulchan commented on apps/company/pages/_app.tsx
> +            <Component {...pageProps} />
이 부분 global 지우시고 emotion style provider 을 사용해 주세요

2022-07-01 07:02 UTC, Josanghyeon approved these changes
굳

2022-07-04 01:38 UTC, justinlee05 commented on apps/company/styles/globalStyle.ts
> +`;
https://github.com/EntryDSM/Buldak/pull/16 부분에서 적용하였습니다

2022-07-04 01:39 UTC, justinlee05 commented on apps/company/pages/_app.tsx
> +            <Component {...pageProps} />
https://github.com/EntryDSM/Buldak/pull/16 부분에서 적용하였습니다

2022-07-04 09:56 UTC, paperdeer approved these changes

2022-07-04 12:38 UTC, justinlee05 commented on apps/company/styles/globalStyle.ts
> +export default globalStyles;
https://github.com/EntryDSM/Buldak/pull/16 부분에서 적용하였습니다

2022-07-04 12:53 UTC, kimulchan approved these changes

2022-07-04 12:53 UTC, merged