merge(company) : 메인 페이지 및 모달 퍼블리싱
EntryDSM/Buldak pull request #16
Opened 2022-06-30 07:57 UTC by justinlee05

2022-06-30 08:13 UTC, paperdeer commented on apps/company/components/editmodal/EditModal.tsx
> +    background-color: #ffffff;
테마값을 사용해주세요!

2022-06-30 08:13 UTC, paperdeer commented on apps/company/components/editmodal/EditModal.tsx
> +const BoxImg = styled.div<{ backgroundImg: any }>`
타입지정 해주세요!

2022-06-30 08:13 UTC, paperdeer commented on apps/company/components/editmodal/EditModal.tsx
> +const Exit = styled.div<{ backgroundImg: any }>`
이것도 타입..

2022-06-30 08:13 UTC, paperdeer commented on apps/company/components/studentbox/StudentBox.tsx
> +    tags: any;
이거도 string 타입이면 될거 같아요

2022-06-30 08:13 UTC, paperdeer commented on apps/company/components/studentbox/StudentBox.tsx
> +                <h1 id="major">프론트엔드</h1>
h1 태그보다 strong이나 em은 어떨까요??

2022-06-30 08:13 UTC, paperdeer commented on apps/company/pages/_app.tsx
> +}
템플릿을 확인해주세요!

2022-06-30 08:13 UTC, paperdeer commented on apps/company/styles/globalStyle.ts
> +export default globalStyles;
style provider를 사용해주세요!

2022-06-30 14:01 UTC, hyejun0608 reviewed
굿굿굿

2022-06-30 14:01 UTC, hyejun0608 commented on apps/company/components/studentbox/StudentBox.tsx
> +            color: #343434;
theme에 black으로 있더라고요

2022-06-30 14:01 UTC, hyejun0608 commented on apps/company/components/studentbox/StudentBox.tsx
> +            color: #b6b6b6;
theme에 gray700으로 있어용

2022-06-30 14:01 UTC, hyejun0608 commented on apps/company/pages/list/index.tsx
> +                    <div></div>
이 div는 필요해서 있는거겠죠..?

2022-06-30 14:11 UTC, justinlee05 commented on apps/company/pages/list/index.tsx
> +                    <div></div>
X버튼 들어갈 자리였습니다!

2022-07-01 00:15 UTC, hxxnim approved these changes
👏👏

2022-07-01 01:58 UTC, paperdeer approved these changes
좋아요

2022-07-01 02:48 UTC, kimulchan requested changes

2022-07-01 02:48 UTC, kimulchan commented on _templates/service/new/next.config.ejs.t
> +const withTM = require("next-transpile-modules")(["ui","@packages/emotion-style-provider"]);
이쪽 ui 부분을 @packages/ui 로 바꿔주세요

2022-07-01 02:48 UTC, kimulchan commented on apps/company/components/editmodal/EditModal.tsx
> +    height: 100vh;
background vh 로 안해도 position absolute 주시고 값을 100% 주는것이 좀 더 좋아 보입니다!

2022-07-01 02:48 UTC, kimulchan commented on apps/company/pages/list/index.tsx
> +
provider 로 감싸서 theme 를 사용해주셨으면 좋겠습니다!

2022-07-01 02:48 UTC, kimulchan commented on apps/company/pages/list/index.tsx
> +
이거 하나만 한게 아니라 프로젝트 전체 한번씩 보면서 바꿔주세요!

2022-07-01 07:02 UTC, Josanghyeon approved these changes
굿 좋습니다

2022-07-04 01:37 UTC, justinlee05 commented on apps/company/pages/list/index.tsx
> +
provider로는 감싸져 있고 저 부분은 theme에 해당하는 색이 없어서 그냥 사용했었습니다. 저런 경우는 어떻게 하면 좋을까요?

2022-07-04 12:53 UTC, kimulchan approved these changes

2022-07-04 12:57 UTC, merged