merge(teacher): pdf 모달 추가
EntryDSM/Buldak pull request #20
Opened 2022-07-01 01:44 UTC by paperdeer

2022-07-01 01:48 UTC, hyejun0608 approved these changes
굿

2022-07-01 02:35 UTC, kimulchan requested changes

2022-07-01 02:35 UTC, kimulchan commented on apps/teacher/components/student/pdf/studentList.tsx
> +                    return <StudentBox item={newItem} />;
여기 왜 타입 단언을 했나요?

2022-07-01 05:29 UTC, Josanghyeon approved these changes
굳

2022-07-03 15:23 UTC, kimulchan approved these changes

2022-07-03 15:23 UTC, kimulchan commented on apps/teacher/components/student/pdf/StudentBox.tsx
> +const _MinusButton = styled(_PlusButton)``;
구지 이렇게 나눈 이유가 있나요??

2022-07-03 15:23 UTC, kimulchan commented
approve 는 눌렀으니까 위에거 한번만 확인하고 머지하세요! 수고하셨습니다!!

2022-07-03 15:35 UTC, merged