merge(teacher): api 관련 함수들 추가
EntryDSM/Buldak pull request #50
Opened 2022-07-12 16:04 UTC by paperdeer

2022-07-13 09:47 UTC, justinlee05 approved these changes

2022-07-13 14:36 UTC, Josanghyeon reviewed
이거 좀 줄여도 되지 않나요?

2022-07-13 14:36 UTC, Josanghyeon commented on apps/teacher/api/axios.ts
> +    timeout: 10000,
10000이나 줘야하나요?

2022-07-13 23:10 UTC, paperdeer commented on apps/teacher/api/axios.ts
> +    timeout: 10000,
10000 ms면 10초인데

2022-07-13 23:33 UTC, kimulchan requested changes
url 부분은 살짝 고민해 볼 필요가 있을 것 같아요. 우선 한 파일안에 전부 관리하는 방법은 사용해야 할 거 같아요. 그래야지 api가 변경되었을 때 빠르게 찾고 수정할 수 있을 것 같아요.

2022-07-13 23:56 UTC, kimbuckgur approved these changes
수고하셨습니다

2022-07-14 08:13 UTC, kimulchan approved these changes

2022-07-14 08:14 UTC, merged