merge(Main): Login API 연결
EntryDSM/Buldak pull request #55
Opened 2022-08-28 02:19 UTC by kimbuckgur

2022-08-28 11:15 UTC, paperdeer requested changes

2022-08-28 11:15 UTC, paperdeer commented on apps/main/pages/FirstLoginPage/Company/StageTwo.tsx
>      const onChangeImg = (event: any) => {
any..?

2022-08-28 11:15 UTC, paperdeer commented on apps/main/pages/FirstLoginPage/Company/StageTwo.tsx
> +            axios({ url: 'http://114.108.176.85:8080/users/first-password', method: 'patch' });
이렇게 모든 api 호출에서 axios 쓸거에요?

2022-08-28 11:15 UTC, paperdeer commented on apps/main/pages/FirstLoginPage/Student/StageOne.tsx
> +        })
너무 불편해보여요

2022-08-30 00:38 UTC, kimbuckgur commented on apps/main/pages/FirstLoginPage/Student/StageOne.tsx
> +        })
어떻게 불편해 보이나요?

2022-08-31 06:19 UTC, paperdeer commented on apps/main/pages/FirstLoginPage/Student/StageOne.tsx
> +        })
모든 axios호출에서 url쓰고, method쓰고 하는게..

2022-09-07 12:28 UTC, kimulchan approved these changes

2022-09-12 14:03 UTC, paperdeer approved these changes

2022-09-17 16:32 UTC, merged